### ISSUE TITLE
Reimplement /calladmin

### ISSUE THREAD

**Issue by BenWoodford** [LoadingChunks/PushEnder#1]
Go nuts.

**Comment by lunasorcery** [comment]
Could you assign this away from me (or even close it since the project has been dead for a while) so it's not cluttering my issues list? Thanks.

EDIT: apparently my commenting has had the side-effect of un-assigning me. :woman_shrugging:

**Comment by BenWoodford** [comment]
¯\\\_(ツ)\_/¯
